#!/bin/bash

set -e

sshpass -p ceph ssh-copy-id node1

mkdir -p  /home/ceph/ceph-cluster && cd /home/ceph/ceph-cluster
pwd
ceph-deploy -v  new  --cluster-network 192.168.200.0/24 --public-network 192.168.200.0/24   node1
cat /vagrant/etc/ceph.conf >> /home/ceph/ceph-cluster/ceph.conf
cat /home/ceph/ceph-cluster/ceph.conf
ceph-deploy -v install --no-adjust-repos node1

ceph-deploy mon create-initial
ssh node1 sudo chmod +r /etc/ceph/ceph.client.admin.keyring
ssh node1 ceph mon stat
set +e
echo "Double check for drive"
ssh node1 sudo umount /dev/sdb1
ssh node1 sudo umount /dev/sdb2
ssh node1 sudo parted /dev/sdb print
set -e
echo
echo "Zapping drives"
ceph-deploy disk zap node1:sdb
ssh node1 sudo parted /dev/sdb print

echo
echo "Preparing drives"
ceph-deploy disk prepare node1:sdb:/dev/sdb
#--dmcrypt --dmcrypt-key-dir=/root --fs-type=xfs
ssh node1 sudo parted /dev/sdb print
sleep 5
ceph-deploy -v disk activate node1:/dev/sdb1:/dev/sdb2
sleep 5
ssh node1 ceph -s
