#!/bin/bash

set -e
runall() {
  echo mng
  $@
  run "$@"
}

#sudo yum install epel-release -y
#sudo yum install sshpass vim -y
#echo "192.168.20.1 mng" | sudo tee -a  /etc/hosts
#echo "192.168.20.11 node1" | sudo tee -a  /etc/hosts
#echo "192.168.20.12 node2" | sudo tee -a  /etc/hosts
#echo "192.168.20.13 node3" | sudo tee -a  /etc/hosts
#
#echo "StrictHostKeyChecking no" | sudo tee -a /etc/ssh/ssh_config
#echo "UserKnownHostsFile=/dev/null" | sudo tee -a /etc/ssh/ssh_config
#
#cd
#mkdir -p  .ssh
#ssh-keygen -t rsa -N "" -f .ssh/id_rsa
#sshpass -p ceph ssh-copy-id node1
#sshpass -p ceph ssh-copy-id node2
#sshpass -p ceph ssh-copy-id node3
#
#run mkdir -p .ssh
#echo "Generating ssh keys on nodes"
#run "ssh-keygen -t rsa -N '' -f .ssh/id_rsa"



#run sudo yum clean all
#run sudo yum install epel-release -y
#run sudo yum install vim -y

#for n in 1 2 3; do scp /etc/hosts node$n:;done
#run sudo cp hosts /etc/hosts

#sudo rpm -Uhv http://download.ceph.com/rpm-hammer/el7/noarch/ceph-release-1-1.el7.noarch.rpm
#sudo yum update -y && sudo yum install ceph-deploy -y
mkdir -p  ~/ceph-cluster && cd ~/ceph-cluster
#ceph-deploy  -v   new  --cluster-network 192.168.40.0/24 --public-network 192.168.60.0/24   node1

#ceph-deploy  -v  install --no-adjust-repos --repo  node{1,2,3}
#ceph-deploy   -v install --no-adjust-repos   node{1,2,3}

#ceph-deploy mon create-initial
#ssh node1 sudo chmod +r /etc/ceph/ceph.client.admin.keyring
#ssh node1 ceph -s
#for n in node{1..3}; do ceph-deploy disk zap $n:sdb;done

#for n in node{1..3}; do ceph-deploy disk prepare $n:sdb:/dev/sdb;done
#sleep 10
#for n in node{1..3}; do ceph-deploy -v disk activate $n:/dev/sdb1:/dev/sdb2;done
#sleep 10

