# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end
  config.ssh.username = "ceph"
  config.ssh.password = "ceph"

  config.vm.define "node1" do |node1|
    node1.vm.box = "kujira/centos7_node1"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.100.11", virtualbox__intnet: "admin_net"
    node1.vm.network "private_network", ip: "192.168.200.11", virtualbox__intnet: "ceph_net"
  end

  config.vm.define "node2" do |node|
    node.vm.box = "kujira/centos7_node2"
    node.vm.hostname = "node2"
    node.vm.network "private_network", ip: "192.168.100.12", virtualbox__intnet: "admin_net"
    node.vm.network "private_network", ip: "192.168.200.12", virtualbox__intnet: "ceph_net"
  end


  config.vm.define "mng" do |mng|
    mng.vm.box = "kujira/centos7_mng"
    mng.vm.hostname = "mng"
    mng.vm.network "private_network", ip: "192.168.100.1", virtualbox__intnet: "admin_net"
  end
end
